#!/usr/bin/env bash
set -eu -o pipefail
trap 'echo 1>&2 "INTERNAL FAILURE!"; exit 3;' 0

die() {
    local exitcode=$1; shift
    echo 1>&2 "FAIL: $@"
    trap '' 0; exit $exitcode
}

BASEDIR=$(cd $(dirname "$0") && pwd -P)
cd "$BASEDIR"

echo '───── Unit Tests'
stack test --ta "$*" || die 1 "Unit tests"
echo

echo '───── Functional Tests'
mkdir -p .build/test/
stack run ml-tableau -- < ftest/1.input > .build/test/1.output \
    || die 2 "ml-tableau error: exit code = $?"
diff -u ftest/1.expected .build/test/1.output \
    || die 1 "ml-tableau produced unexpected output"

echo 'PASSED'
trap '' 0   # No internal failure.
