#!/usr/bin/env bash
set -eu -o pipefail
trap 'echo 1>&2 "INTERNAL FAILURE!"; exit 3;' 0

die() {
    local exitcode=$1; shift
    echo 1>&2 "FAIL: $@"
    trap '' 0; exit $exitcode
}

BASEDIR=$(cd $(dirname "$0") && pwd -P)
cd "$BASEDIR"

echo '───── Unit Tests'
stack test --ta "$*" || die 1 "Unit tests"
echo

echo '───── Functional Tests'
stack run ml-tableau -- < ftest/1.input | diff -u ftest/1.expected -

echo 'PASSED'
trap '' 0   # No internal failure.
