#!/usr/bin/env bash

set -eu -o pipefail
REPO_DIR="$(cd $(dirname $0)/..; pwd)"
DOC_DIR="$REPO_DIR/docs"
BUILD_DIR="$REPO_DIR/.build"

cd "$DOC_DIR"

mkdir -p "$BUILD_DIR"
pandoc --standalone -t latex -o "$BUILD_DIR/tableau.pdf" \
       --citeproc --table-of-contents \
       "$DOC_DIR"/preliminaries.md "$DOC_DIR"/tableau.md \
       -V header-includes="\include{prelude.tex}" \
       -V template="$DOC_DIR/template.tex" \
       -F pandocfilters/defenv.py
